Name = "All-In-One OTF Configuration"
Port = 1555
API = "/otf-config"
PageFolder = "public"

[[NatsStreamings]]
  Name = "ns_config"
  Path = "~/Desktop/OTF/nats-streaming-server-v0.22.0-linux-amd64/nats-streaming-server"
  Args = "test args 11"
  Delay = "3,10"

[[Nias3s]]
  Name = "n3_config"
  Path = "~/Desktop/OTF/n3-web/server/n3w/n3w"
  Args = ""
  Delay = "1,5"

[[Benthoses]]
  Name = "benthos_align"
  Path = "~/Desktop/OTF/benthos3470/benthos"
  Args = "-c ~/Desktop/OTF/otf-hub/benthos/maps/align.yaml"
  Delay = ""

[[Benthoses]]
  Name = "benthos_level"
  Path = "~/Desktop/OTF/benthos3470/benthos"
  Args = "-c ~/Desktop/OTF/otf-hub/benthos/maps/level.yaml"
  Delay = ""

[[Benthoses]]
  Name = "benthos_data"
  Path = "~/Desktop/OTF/benthos3470/benthos"
  Args = "-c ~/Desktop/OTF/otf-hub/benthos/data.yaml"
  Delay = ""

[[Readers]]
  Name = "spa_prescribed_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/spa"
  Delay = ""
  SvrName = ""
  SvrID = ""
  Provider = "SPA"
  InputFmt = "csv"
  AlignMethod = "prescribed"
  LevelMethod = "prescribed"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".prescribed.csv"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "spa_mapped_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/spa"
  Delay = ""
  SvrName = ""
  SvrID = ""
  Provider = "SPA"
  InputFmt = "csv"
  AlignMethod = "mapped"
  LevelMethod = "prescribed"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".mapped.csv"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "mp_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/maths-pathway"
  Delay = ""
  SvrName = ""
  SvrID = ""
  Provider = "MathsPathway"
  InputFmt = "csv"
  AlignMethod = "mapped"
  LevelMethod = "prescribed"
  GenCapability = "numeracy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".csv"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "lpofa_numeracy_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/lpofa"
  Delay = ""
  SvrName = ""
  SvrID = ""
  Provider = "LPOFA"
  InputFmt = "json"
  AlignMethod = "inferred"
  LevelMethod = "prescribed"
  GenCapability = "numeracy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".numeracy.json"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "lpofa_literacy_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/lpofa"
  Delay = ""
  SvrName = ""
  SvrID = ""
  Provider = "LPOFA"
  InputFmt = "json"
  AlignMethod = "inferred"
  LevelMethod = "prescribed"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".literacy.json"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "bp_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/brightpath"
  Delay = ""
  SvrName = ""
  SvrID = ""
  Provider = "BrightPath"
  InputFmt = "json"
  AlignMethod = "mapped"
  LevelMethod = "mapped"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".brightpath"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "levelMaps_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/maps/level"
  Delay = ""
  SvrName = ""
  SvrID = ""
  Provider = "nsip"
  InputFmt = "csv"
  AlignMethod = "mapped"
  LevelMethod = "mapped"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.maps.level"
  Folder = ""
  FileSuffix = ".csv"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "alignMaps_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/maps/align"
  Delay = ""
  SvrName = ""
  SvrID = ""
  Provider = "nsip"
  InputFmt = "csv"
  AlignMethod = "mapped"
  LevelMethod = "mapped"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.maps.align"
  Folder = ""
  FileSuffix = ".csv"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Aligns]]
  Name = "align_config"
  Path = "~/Desktop/OTF/otf-align/cmd/otf-align/otf-align"
  Args = ""
  Delay = ""
  SvrName = ""
  SvrID = ""
  Host = ""
  Port = 1234
  NiasHost = ""
  NiasPort = 1323
  NiasToken = ""
  TcHost = ""
  TcPort = 1576

[[TxtClassifiers]]
  Name = "tc_config"
  Path = "~/Desktop/OTF/otf-classifier/build/Linux64/otf-classifier/otf-classifier"
  Args = ""
  Delay = ""
  Port = 1458

[[Levels]]
  Name = "level_config"
  Path = "~/Desktop/OTF/otf-level/cmd/otf-level/otf-level"
  Args = ""
  Delay = ""
  SvrName = ""
  SvrID = ""
  Host = ""
  Port = 1234
  NiasHost = ""
  NiasPort = 1323
  NiasToken = ""

[[Weights]]
  Name = "weight_config"
  Path = "~/Desktop/OTF/otf-weighting/otf-weighting"
  Args = ""
  Delay = ""
  FailWhenErr = false
  [Weights.Service]
    SvrName = ""
    SvrID = ""
    Port = 1329
    API = "/weight"
  [Weights.Weighting]
    StudentIDPath = "otf.id.studentID"
    DomainPath = "meta.capability"
    TimePath = "meta.readTimestampUTC"
    ScorePath = "otf.level.calculatedScore.scaledScore"

[[Hubs]]
  Name = "hub_config"
  Path = "~/Desktop/OTF/otf-hub/hub/hub"
  ComTbl = "88888"
