Name = "All-In-One OTF Configuration"
Port = 1555
API = "/otf-config"
PageFolder = "public"

[[NatsStreamings]]
  Name = "ns_config"
  Path = "~/Desktop/OTF/nats-streaming-server-v0.22.0-linux-amd64/nats-streaming-server"
  Args = ""
  Delay = "0,10"

[[Nias3s]]
  Name = "n3_config"
  Path = "~/Desktop/OTF/n3-web/server/n3w/n3w"
  Args = ""
  Delay = "1,2"

[[Benthoses]]
  Name = "benthos_align"
  Path = "~/Desktop/OTF/benthos3480/benthos"
  Args = "-c ~/Desktop/OTF/otf-hub/benthos/maps/align.yaml"
  Delay = "3"

[[Benthoses]]
  Name = "benthos_level"
  Path = "~/Desktop/OTF/benthos3480/benthos"
  Args = "-c ~/Desktop/OTF/otf-hub/benthos/maps/level.yaml"
  Delay = "3"

[[Benthoses]]
  Name = "benthos_data"
  Path = "~/Desktop/OTF/benthos3480/benthos"
  Args = "-c ~/Desktop/OTF/otf-hub/benthos/data.yaml"
  Delay = "3"

[[Readers]]
  Name = "spa_prescribed_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/OTF/otf-hub/in/spa --config=./spa_prescribed_config.json"
  Delay = "2"
  SvrName = ""
  SvrID = ""
  Provider = "SPA"
  InputFmt = "csv"
  AlignMethod = "prescribed"
  LevelMethod = "prescribed"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".prescribed.csv"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "spa_mapped_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/OTF/otf-hub/in/spa --config=./spa_mapped_config.json"
  Delay = "2"
  SvrName = ""
  SvrID = ""
  Provider = "SPA"
  InputFmt = "csv"
  AlignMethod = "mapped"
  LevelMethod = "prescribed"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".mapped.csv"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "mp_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/OTF/otf-hub/in/maths-pathway --config=./mp_config.json"
  Delay = "2"
  SvrName = ""
  SvrID = ""
  Provider = "MathsPathway"
  InputFmt = "csv"
  AlignMethod = "mapped"
  LevelMethod = "prescribed"
  GenCapability = "numeracy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".csv"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "lpofa_numeracy_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/OTF/otf-hub/in/lpofa --config=./lpofa_numeracy_config.json"
  Delay = "2"
  SvrName = ""
  SvrID = ""
  Provider = "LPOFA"
  InputFmt = "json"
  AlignMethod = "inferred"
  LevelMethod = "prescribed"
  GenCapability = "numeracy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".numeracy.json"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "lpofa_literacy_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/OTF/otf-hub/in/lpofa --config=./lpofa_literacy_config.json"
  Delay = "2"
  SvrName = ""
  SvrID = ""
  Provider = "LPOFA"
  InputFmt = "json"
  AlignMethod = "inferred"
  LevelMethod = "prescribed"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".literacy.json"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "bp_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/OTF/otf-hub/in/brightpath --config=./bp_config.json"
  Delay = "2"
  SvrName = ""
  SvrID = ""
  Provider = "BrightPath"
  InputFmt = "json"
  AlignMethod = "mapped"
  LevelMethod = "mapped"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.ingest"
  Folder = ""
  FileSuffix = ".brightpath"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "levelMaps_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/OTF/otf-hub/in/maps/level --config=./levelMaps_config.json"
  Delay = "2"
  SvrName = ""
  SvrID = ""
  Provider = "nsip"
  InputFmt = "csv"
  AlignMethod = "mapped"
  LevelMethod = "mapped"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.maps.level"
  Folder = ""
  FileSuffix = ".csv"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Readers]]
  Name = "alignMaps_config"
  Path = "~/Desktop/OTF/otf-reader/cmd/otf-reader/otf-reader"
  Args = "--folder=~/Desktop/OTF/otf-hub/in/maps/align --config=./alignMaps_config.json"
  Delay = "2"
  SvrName = ""
  SvrID = ""
  Provider = "nsip"
  InputFmt = "csv"
  AlignMethod = "mapped"
  LevelMethod = "mapped"
  GenCapability = "literacy"
  NatsHost = ""
  NatsPort = 4222
  NatsCluster = ""
  Topic = "otf.maps.align"
  Folder = ""
  FileSuffix = ".csv"
  Interval = "500ms"
  Recursive = true
  DotFiles = false
  Ignore = ""
  ConcurrFiles = 10

[[Aligns]]
  Name = "align_config"
  Path = "~/Desktop/OTF/otf-align/cmd/otf-align/otf-align"
  Args = ""
  Delay = "2"
  SvrName = ""
  SvrID = ""
  Host = ""
  Port = 1324
  NiasHost = "127.0.0.1"
  NiasPort = 1323
  NiasToken = ""
  TcHost = "127.0.0.1"
  TcPort = 1576

[[TxtClassifiers]]
  Name = "tc_config"
  Path = "~/Desktop/OTF/otf-classifier/build/Linux64/otf-classifier/otf-classifier"
  Args = ""
  Delay = "2"
  Port = 1576

[[Levels]]
  Name = "level_config"
  Path = "~/Desktop/OTF/otf-level/cmd/otf-level/otf-level"
  Args = ""
  Delay = "2"
  SvrName = ""
  SvrID = ""
  Host = ""
  Port = 1327
  NiasHost = "127.0.0.1"
  NiasPort = 1323
  NiasToken = ""

[[Weights]]
  Name = "weight_config"
  Path = "~/Desktop/OTF/otf-weighting/otf-weighting"
  Args = "test"
  Delay = "2"
  FailWhenErr = false
  InType = "json"
  MustInArray = false
  In = "./in"
  InTemp = "./temp"
  Out = "./out"
  OutType = "json"
  [Weights.Service]
    SvrName = "test"
    SvrID = "testid"
    Port = 1329
    API = "/weight"
  [Weights.Weighting]
    StudentIDPath = "otf.id.studentID"
    ProgressionLevelPath = "otf.progressionLevel"
    TimePath0 = "original.test.date_administered"
    TimePath1 = "meta.readTimestampUTC"
    ScorePath = "otf.level.calculatedScore.scaledScore"

[[Hubs]]
  Name = "hub_config"
  Path = "~/Desktop/OTF/otf-hub/hub/hub"
  ComTbl = "services4"
